### ISSUE TITLE
Show fuzzy dates and times

### ISSUE THREAD

**Issue by amshali** [w7cook/OpenBook#145]
Use this jQuery plugin for showing dates:
http://timeago.yarp.com/

**Comment by pk1m** [comment]
.gcmgzc

**Comment by amshali** [comment]
What?

**Comment by jtessler** [comment]
Reopening the issue given Amin's request to use the jQuery plugin.

**Comment by amshali** [comment]
Yes.

**Comment by jtessler** [comment]
After importing timeago and updating various templates, I find this:
http://www.playframework.org/documentation/1.1.1/javaextensions

Play added a `since()` method to `Date`, so you can just call that to
produce the fuzzy dates. Not sure about future dates though... I feel
like someone robbed my time.

**Comment by jtessler** [comment]
What do you think of the two implementations? I can pull either one to master.

**Comment by amshali** [comment]
Sorry what is the second one?

**Comment by jtessler** [comment]
https://github.com/jtessler/OpenBook/compare/w7cook:master...fuzzy_dates_timeago

**Comment by amshali** [comment]
I like timeago plugin better because it's on the client side and at the end we need that for refreshing the dates.

**Comment by jtessler** [comment]
Not sure why the pull request didn't auto-close this...
