### ISSUE TITLE
Birthday's not set in initial data

### ISSUE THREAD

**Issue by ProCynic** [w7cook/OpenBook#273]
I'm trying to fix the birthday thing but I can't test it because there's no birthdays in the database.

**Comment by ghost** [comment]
Yeah, be aware that since birthday data hasn't really been available recently, I currently have it set so that all friends' birthdays are marked as today in the UpcomingBirthdays controller (you'll see the commented part). That's just for testing/showing the feature.
Once data starts running in, we can remove that

**Comment by ProCynic** [comment]
Check out what I did here: https://github.com/ProCynic/OpenBook/tree/html
I think it's a lot cleaner, both in the UI and the back end.
I deleted all the UpcomingBirthday files, removed the iframe, and replaced it with a simple list of users, capped at 5.
The controller has been replaced with 2 one line methods at the bottom of User.java
I also converted the send to wall modal to bootstrap so that we don't have to import additional js.
